CREATE TABLE maintenancetracker_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    landlord_tenant TEXT,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    password TEXT
)